In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("StudentsPerformance.csv")
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

df.sort_values("math score", ascending=False).head(10)
# sort_values() — sorts a DataFrame by one or more columns
# syntax: df.sort_values("column", ascending=False)
# ascending=True  → lowest to highest (default)
# ascending=False → highest to lowest

In [4]:
df.sort_values("writing score").head(5)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
59,female,group C,some high school,free/reduced,none,0,17,10
596,male,group B,high school,free/reduced,none,30,24,15
327,male,group A,some college,free/reduced,none,28,23,19
76,male,group E,some high school,standard,none,30,26,22
980,female,group B,high school,free/reduced,none,8,24,23

In [5]:
df.sort_values(["gender", "math score"], ascending=[True, False])
# Multiple columns: df.sort_values(["col1", "col2"], ascending=[True, False])

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
451,female,group E,some college,standard,none,100,92,97
458,female,group E,bachelor's degree,standard,none,100,100,100
962,female,group E,associate's degree,standard,none,100,100,100
114,female,group E,bachelor's degree,standard,completed,99,100,100
263,female,group E,high school,standard,none,99,93,90
...,...,...,...,...,...,...,...,...
211,male,group C,some college,free/reduced,none,35,28,27
76,male,group E,some high school,standard,none,30,26,22
596,male,group B,high school,free/reduced,none,30,24,15
327,male,group A,some college,free/reduced,none,28,23,19
91,male,group C,high school,free/reduced,none,27,34,36

In [6]:
df["race/ethnicity"].shape[0]
# shape tells you the size of the whole DataFrame — rows and columns

1000

In [7]:
df["race/ethnicity"].value_counts()
# value_counts() tells you how many times each unique category appears in one specific column

race/ethnicity
group C    319
group D    262
group B    190
group E    140
group A     89
Name: count, dtype: int64

In [8]:
df["test preparation course"].value_counts()

test preparation course
none         642
completed    358
Name: count, dtype: int64